In [318]:
import numpy as np

X = np.array([[1, 1, -1, 0, 2],
                 [0, 0, 1, 2, 0],
                 [-1, -1, 1, 1, 0],
                 [4, 0, 1, 2, 1],
                 [-1, 1, 1, 1, 0],
                 [-1, -1, -1, 1, 0],
                 [-1, 1, 1, 2, 1]])

#INSERT EXTRA
Y = np.insert(X, obj=0, values=1, axis = 1)

a = np.array([3,1,1,-1,2,-7])
labels = np.array(['w2','w1','w2','w1','w1','w1','w2'])

In [319]:
X

array([[ 1,  1, -1,  0,  2],
       [ 0,  0,  1,  2,  0],
       [-1, -1,  1,  1,  0],
       [ 4,  0,  1,  2,  1],
       [-1,  1,  1,  1,  0],
       [-1, -1, -1,  1,  0],
       [-1,  1,  1,  2,  1]])

In [320]:
labels

array(['w2', 'w1', 'w2', 'w1', 'w1', 'w1', 'w2'], dtype='<U2')

In [321]:
Y

array([[ 1,  1,  1, -1,  0,  2],
       [ 1,  0,  0,  1,  2,  0],
       [ 1, -1, -1,  1,  1,  0],
       [ 1,  4,  0,  1,  2,  1],
       [ 1, -1,  1,  1,  1,  0],
       [ 1, -1, -1, -1,  1,  0],
       [ 1, -1,  1,  1,  2,  1]])

## AUGMENTATION

In [322]:
# Augmentation
Y[labels == 'w2'] = Y[labels == 'w2'] * -1

In [323]:
Y

array([[-1, -1, -1,  1,  0, -2],
       [ 1,  0,  0,  1,  2,  0],
       [-1,  1,  1, -1, -1,  0],
       [ 1,  4,  0,  1,  2,  1],
       [ 1, -1,  1,  1,  1,  0],
       [ 1, -1, -1, -1,  1,  0],
       [-1,  1, -1, -1, -2, -1]])

In [324]:
i = 0
while True:
    for _, y in enumerate(Y):
            # calculating yta
            i = i+1
            ydota = y.dot(a)
            miss = 'Y' if ydota<0 else 'N'
            if ydota < 0:
            
                print(f"STEP: {i}, y: {y}, a{i}: {a}, a{i+1}= {a+y}, ydota= {ydota} , missclassfied = {miss}"
                     )
                a = a + y
            else:
                print(f"STEP: {i}, y: {y}, a{i}: {a}, a{i+1}= {a}, ydota= {ydota} , missclassfied = {'Y' if ydota<0 else 'N'}"
                     )
    if (Y.dot(a)<0).sum() == 0:
        break

STEP: 1, y: [-1 -1 -1  1  0 -2], a1: [ 3  1  1 -1  2 -7], a2= [ 3  1  1 -1  2 -7], ydota= 8 , missclassfied = N
STEP: 2, y: [1 0 0 1 2 0], a2: [ 3  1  1 -1  2 -7], a3= [ 3  1  1 -1  2 -7], ydota= 6 , missclassfied = N
STEP: 3, y: [-1  1  1 -1 -1  0], a3: [ 3  1  1 -1  2 -7], a4= [ 2  2  2 -2  1 -7], ydota= -2 , missclassfied = Y
STEP: 4, y: [1 4 0 1 2 1], a4: [ 2  2  2 -2  1 -7], a5= [ 2  2  2 -2  1 -7], ydota= 3 , missclassfied = N
STEP: 5, y: [ 1 -1  1  1  1  0], a5: [ 2  2  2 -2  1 -7], a6= [ 2  2  2 -2  1 -7], ydota= 1 , missclassfied = N
STEP: 6, y: [ 1 -1 -1 -1  1  0], a6: [ 2  2  2 -2  1 -7], a7= [ 2  2  2 -2  1 -7], ydota= 1 , missclassfied = N
STEP: 7, y: [-1  1 -1 -1 -2 -1], a7: [ 2  2  2 -2  1 -7], a8= [ 2  2  2 -2  1 -7], ydota= 5 , missclassfied = N


In [325]:
a

array([ 2,  2,  2, -2,  1, -7])

In [326]:
X

array([[ 1,  1, -1,  0,  2],
       [ 0,  0,  1,  2,  0],
       [-1, -1,  1,  1,  0],
       [ 4,  0,  1,  2,  1],
       [-1,  1,  1,  1,  0],
       [-1, -1, -1,  1,  0],
       [-1,  1,  1,  2,  1]])

In [327]:
a

array([ 2,  2,  2, -2,  1, -7])

In [328]:
Y

array([[-1, -1, -1,  1,  0, -2],
       [ 1,  0,  0,  1,  2,  0],
       [-1,  1,  1, -1, -1,  0],
       [ 1,  4,  0,  1,  2,  1],
       [ 1, -1,  1,  1,  1,  0],
       [ 1, -1, -1, -1,  1,  0],
       [-1,  1, -1, -1, -2, -1]])

In [333]:
X.dot(a[1:])<(a[0]*-1)

array([ True, False,  True, False, False, False,  True])

In [330]:
labels

array(['w2', 'w1', 'w2', 'w1', 'w1', 'w1', 'w2'], dtype='<U2')